FROM plugins/base:i386

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" \
  org.label-schema.name="Drone Scalingo" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

RUN apk add --no-cache git openssh curl perl

ADD release/linux/i386/drone-scalingo /bin/
ENTRYPOINT ["/bin/drone-scalingo"]
